=== David-Sec-s9897/aplan-mock/src/main/resources/xsd/SubmissionStatus.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema 
	xmlns="http://www.grid-applications.com/documents/submission-status"
	targetNamespace="http://www.grid-applications.com/documents/submission-status"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" 
	elementFormDefault="qualified">
	
	<xs:element name="SubmissionStatus" type="SubmissionStatusType"/>
	
	<xs:complexType name="ElementValueStringType">
		<xs:attribute name="v" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="ElementValueIntegerType">
		<xs:attribute name="v" type="xs:integer" use="required"/>
	</xs:complexType>
	
	<xs:simpleType name="StatusType">
	  	<xs:restriction base="xs:string">
	    	<xs:pattern value="(IN PROGRESS)|(SUCCESS)|(ERROR)"/>
	  	</xs:restriction>
	</xs:simpleType> 
	
	<xs:complexType name="ElementValueStatusType">
		<xs:attribute name="v" type="StatusType" use="required"/>
	</xs:complexType>
	
	<xs:simpleType name="YMDHMSDateTime">
	    <xs:restriction base="xs:string">
	     	<xs:pattern value="((([0-9]{4})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])Z)" />
	    </xs:restriction>
  	</xs:simpleType>
	
	<xs:complexType name="ElementValueYMDHMSDateTimeType">
		<xs:attribute name="v" type="YMDHMSDateTime" use="required"/>
	</xs:complexType>
	
	<xs:simpleType name="YMDHMDateTimeRange">
    	<xs:restriction base="xs:string">
      		<xs:pattern value="(((([0-9]{4})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z))/(((([0-9]{4})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z))" />
    	</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="ElementValueYMDHMDateTimeRangeType">
		<xs:attribute name="v" type="YMDHMDateTimeRange" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="RecipientType">
		<xs:sequence>
			<xs:element name="Name" type="ElementValueStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Status" type="ElementValueStatusType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="SubmissionType">
		<xs:sequence>
			<xs:element name="InArea" type="ElementValueStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="OutArea" type="ElementValueStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Recipient" type="RecipientType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="SubmissionStatusType">
		<xs:sequence>
			<xs:element name="DocumentId" type="ElementValueStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="DocumentVersion" type="ElementValueIntegerType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SubmissionDateTime" type="ElementValueYMDHMSDateTimeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="CapacityTimeInterval" type="ElementValueYMDHMDateTimeRangeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Submission" type="SubmissionType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== David-Sec-s9897/aplan-mock/test-requests.http/request-form-data-OK.xml
<?xml version="1.0" encoding="UTF-8"?>
<SubmissionStatus xmlns="http://www.grid-applications.com/documents/submission-status" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.grid-applications.com/documents/submission-status SubmissionStatus.xsd">
    <DocumentId v="2015-000001"/>
    <DocumentVersion v="2"/>
    <SubmissionDateTime v="2024-10-07T08:21:48Z"/>
    <CapacityTimeInterval v="2015-09-01T08:00Z/2015-09-02T10:00Z"/>
    <Submission>
        <InArea v="10YCH-SWISSGRIDZ"/>
        <OutArea v="10YAT-APG------L"/>
        <Recipient>
            <Name v="ENTSO-E Transparency Portal"/>
            <Status v="SUCCESS"/>
        </Recipient>
    </Submission>
    <Submission>
        <InArea v="10YAT-APG------L"/>
        <OutArea v="10YCH-SWISSGRIDZ"/>
        <Recipient>
            <Name v="ENTSO-E Transparency Portal"/>
            <Status v="SUCCESS"/>
        </Recipient>
    </Submission>
</SubmissionStatus>
